import clsx from 'clsx';
import './globals.css';
import type { Metadata } from 'next';
import { Public_Sans } from 'next/font/google';
import localFont from 'next/font/local';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const publicSans = Public_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-public-sans',
});

const gilroy = localFont({
  src: '../fonts/Gilroy-SemiBold.ttf',
  display: 'swap',
  variable: '--font-gilroy-semi-bold',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={clsx(
        'h-full scroll-smooth bg-white antialiased',
        publicSans.variable,
        gilroy.variable
      )}
    >
      <body className='flex h-full flex-col'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
